export type ToolTipPosition = "top" | "bottom" | "left" | "right"
export type AnchorTarget = "_blank" | "_self" | "_parent" | "_top"
export type BadgeVariant = "primary" | "secondary" | "outline"
export type StatusIndicatorVariant = "active" | "busy" | "emergency" | "offline"
export type PopoverPosition =
	| "top"
	| "bottom"
	| "left"
	| "right"
	| "top-right"
	| "top-left"
	| "bottom-right"
	| "bottom-left"
export type ButtonVariant = "primary" | "secondary" | "outline"
export type ButtonSize = "fill" | "default" | "small"
